name: Trigger auto deployment for invsolncontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/invsolncontainerapp-AutoDeployTrigger-52f88ce4-938a-4112-9cfc-f9a92a624fb8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.INVSOLNCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.INVSOLNCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.INVSOLNCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: invsolnacr.azurecr.io
          registryUsername: ${{ secrets.INVSOLNCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.INVSOLNCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: invsolncontainerapp
          resourceGroup: inv_soln
          imageToBuild: invsolnacr.azurecr.io/invsolncontainerapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


